# provider:
#   name: petstore
provider:
  name: cribl

resources:
  input:
    create:
      # path: /m/{groupId}/system/inputs/
      path: /system/inputs
      method: POST
    read:
      # path: /m/{groupId}/system/inputs/{inputId}
      path: /system/inputs/{id}
      method: GET
    update:
      # path: /m/{groupId}/system/inputs/{inputId}
      path: /system/inputs/{id}
      method: PATCH
    delete:
      # path: /m/{groupId}/system/inputs/{inputId}
      path: /system/inputs/{id}
      method: DELETE
    schema:
      attributes:
        #       overrides:
        #         name:
        #           description: The pet's full name
        #         category:
        #           description: Category containing classification info about the pet
        #         "category.name":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name":
        #           description: The category name, possible values - 'dog', 'cat', 'bird', or 'other'
        aliases:
          inputId: id

  # pet:
  #   create:
  #     path: /pet
  #     method: POST
  #   read:
  #     path: /pet/{petId}
  #     method: GET
  #   update:
  #     path: /pet
  #     method: PUT
  #   delete:
  #     path: /pet/{petId}
  #     method: DELETE
  #   schema:
  #     attributes:
  #       overrides:
  #         name:
  #           description: The pet's full name
  #         category:
  #           description: Category containing classification info about the pet
  #         "category.name":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name":
  #           description: The category name, possible values - 'dog', 'cat', 'bird', or 'other'
  #       aliases:
  #         petId: id

  # order:
  #   create:
  #     path: /store/order
  #     method: POST
  #   read:
  #     path: /store/order/{orderId}
  #     method: GET
  #   delete:
  #     path: /store/order/{orderId}
  #     method: DELETE
  #   schema:
  #     attributes:
  #       overrides:
  #         status:
  #           description: Order status, possible values - 'placed', 'approved', or 'delivered'
  #         shipDate:
  #           description: A field representing the date and time an order will be shipped by
  #       aliases:
  #         orderId: id

  user:
    create:
      path: /system/users
      method: POST
    read:
      path: /system/users/{id}
      method: GET
    # schema:
    #   ignores:
    #     - username
    schema:
      attributes:
        # overrides:
        #   name:
        #     description: The pet's full name
        #   category:
        #     description: Category containing classification info about the pet
        #   "category.name":
        #     description: The category name, possible values - 'dog', 'cat', 'bird', or 'other'
        aliases:
          userId: id

data_sources:
  input:
    read:
      # path: /m/{groupId}/system/inputs/{inputId}
      path: /system/inputs/{id}
      method: GET
    schema:
      attributes:
        # overrides:
        #   name:
        #     description: The pet's full name
        #   category:
        #     description: Category containing classification info about the pet
        #   "category.name":
        #     description: The category name, possible values - 'dog', 'cat', 'bird', or 'other'
        aliases:
          inputId: id

  # pet:
  #   read:
  #     path: /pet/{petId}
  #     method: GET
  #   schema:
  #     attributes:
  #       overrides:
  #         name:
  #           description: The pet's full name
  #         category:
  #           description: Category containing classification info about the pet
  #         "category.name":
  #           description: The category name, possible values - 'dog', 'cat', 'bird', or 'other'
  #       aliases:
  #         petId: id

  inputs:
    read:
      # path: /m/{groupId}/system/inputs/
      path: /system/inputs
      method: GET
    schema:
      ignores:
        - status

  # pets:
  #   read:
  #     path: /pet/findByStatus
  #     method: GET
  #   schema:
  #     ignores:
  #       - status

  # order:
  #   read:
  #     path: /store/order/{orderId}
  #     method: GET
  #   schema:
  #     attributes:
  #       overrides:
  #         status:
  #           description: Order status, possible values - 'placed', 'approved', or 'delivered'
  #         shipDate:
  #           description: A field representing the date and time an order will be shipped by
  #       aliases:
  #         orderId: id
