// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_cribl

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func CriblProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type CriblModel struct {
}
